# Path to your oh-my-zsh installation
export ZSH=$HOME/.oh-my-zsh

# Term used
export TERM=vt100

# Theme
ZSH_THEME="gentoo"

# CUSTOM
ZSH_CUSTOM=$HOME/.zsh/custom

# Command execution time stamp shown in the history command output
HIST_STAMPS="dd/mm/yyyy"

# Plugins
plugins=(
    git
    common-aliases
    gitfast
    git-extras
    sudo
    encode64
    pip
    python
    urltools
)

# Activate Oh My ZSH
source $ZSH/oh-my-zsh.sh

# Lang export configuration
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='vim'
fi

# Alias
alias upgrade="sudo aptitude update && sudo aptitude upgrade"
alias sudoe="sudo -E su -p"
